export { default as authApi } from '@/features/shared/auth/api/authApi'
export { default as adminApi } from '@/features/admin/api/adminApi'
export { default as counselorApi } from '@/features/counselor/api/counselorApi'
export { default as mentorApi } from '@/features/mentor/api/mentorApi'
export { default as careerApi } from './careerApi'
export { default as marketPulseApi } from '@/features/student/market-pulse/marketPulseApi'
export { default as dashboardApi } from './dashboardApi'
export { default as roadmapApi } from './roadmapApi'
export { default as userApi } from './userApi'
export { default as skillApi } from './skillApi'
export * from './skillApi'
export { default as profileApi } from './profileApi'
export { default as assessmentApi } from '@/features/student/assessment/assessmentApi'
export * from '@/shared/api'
