spring.application.name=testingTDD

payos.checksum-key=${PAYOS_CHECKSUM_KEY:dummy-checksum-key}
payos.cancel-url=${PAYOS_CANCEL_URL:http://localhost:8080/payment/cancel}
payos.return-url=${PAYOS_RETURN_URL:http://localhost:8080/payment/return}
