/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Chapter2;

/**
 *
 * @author Dinh Dinh
 */
public class BlockTest {

    public static void main(String[] args) {
        int x, y;

        y = 20;
        for (x = 0; x<10; x++) {
            System.out.println("This is x: " + x);
            System.out.println("This is Y: " + y);
            y = y - 2; 
        }
        
        /*
        In this case, the target of the for loop is a block of code and not just a single statement.
        Thus, each time the loop iterates, the three statements inside the block will be executed.
        This fact is, of course, evidenced by the output generated by the program.
        */
    }
}
